name: Build and Run Tests and Lint Files
"on": push
jobs:
  unit_test-lint:
    name: continue integration
    runs-on: ubuntu-20.04
    steps:  
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.18.1
    - run: |
          npm ci
          npm run lintfix
          npm run test
          npm run build
